import { ApiConfig, ExecutionResults } from '../types';

/**
 * Backend Service Layer
 * Handles direct HTTP communication with external APIs.
 */

// --- GitHub ---
export const fetchGitHubCommit = async (config: ApiConfig) => {
  if (!config.githubOwner || !config.githubRepo || !config.githubToken) {
    throw new Error("Missing GitHub configuration");
  }

  const response = await fetch(`https://api.github.com/repos/${config.githubOwner}/${config.githubRepo}/commits?per_page=1`, {
    headers: {
      'Authorization': `token ${config.githubToken}`,
      'Accept': 'application/vnd.github.v3+json'
    }
  });

  if (!response.ok) {
    throw new Error(`GitHub API Error: ${response.status} ${response.statusText}`);
  }

  return await response.json();
};

// --- Slack ---
export const sendSlackNotification = async (config: ApiConfig, message: string) => {
  if (!config.slackWebhook) {
    throw new Error("Missing Slack Webhook URL");
  }

  // Using no-cors mode because Slack webhooks don't return CORS headers for browser fetch.
  await fetch(config.slackWebhook, {
    method: 'POST',
    mode: 'no-cors',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ text: message })
  });

  return true;
};

// --- Gmail (Simulation) ---
export const sendEmail = async (config: ApiConfig, recipient: string, subject: string, body: string) => {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 800));

  if (!config.gmailAddress) {
    throw new Error("Missing Gmail Sender Address configuration");
  }

  console.log(`[Gmail Simulation] Sending to ${recipient} from ${config.gmailAddress}`);
  console.log(`Subject: ${subject}`);
  console.log(`Body: ${body}`);

  return { 
    id: `msg-${Date.now()}`, 
    threadId: `th-${Date.now()}` 
  };
};

// --- Jira ---
export const createJiraTicket = async (config: ApiConfig, results: ExecutionResults) => {
  if (!config.jiraDomain || !config.jiraEmail || !config.jiraToken || !config.jiraProjectKey) {
    throw new Error("Missing Jira configuration");
  }

  // Construct Basic Auth Header
  const auth = btoa(`${config.jiraEmail}:${config.jiraToken}`);

  const bodyData = {
    fields: {
      project: {
        key: config.jiraProjectKey
      },
      summary: `[${results.detectedComponent}] ${results.bugSummary}`,
      description: {
        type: "doc",
        version: 1,
        content: [
          {
            type: "paragraph",
            content: [
              {
                type: "text",
                text: `Auto-generated by Konnect-Ai Agent.\n\nPriority: ${results.bugPriority}\nDetected in Component: ${results.detectedComponent}\n\nRelated Commit: ${results.commitHash}`
              }
            ]
          }
        ]
      },
      issuetype: {
        name: "Bug"
      }
    }
  };

  const response = await fetch(`${config.jiraDomain}/rest/api/3/issue`, {
    method: 'POST',
    headers: {
      'Authorization': `Basic ${auth}`,
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(bodyData)
  });

  if (!response.ok) {
    let errorMsg = `${response.status} ${response.statusText}`;
    try {
      const errBody = await response.json();
      errorMsg += ` - ${JSON.stringify(errBody)}`;
    } catch (e) { /* ignore */ }
    
    throw new Error(`Jira API Error: ${errorMsg}`);
  }

  return await response.json();
};

// --- New Simulations ---

export const scheduleCalendarMeeting = async (config: ApiConfig, title: string, attendees: string[]) => {
  await new Promise(resolve => setTimeout(resolve, 600)); // Sim Delay
  if (!config.calendarId) throw new Error("Missing Calendar ID");
  return {
    link: "https://meet.google.com/abc-defg-hij",
    time: new Date(Date.now() + 3600000).toLocaleString()
  };
};

export const fetchSentryError = async (config: ApiConfig) => {
  await new Promise(resolve => setTimeout(resolve, 500));
  if (!config.sentryDsn) throw new Error("Missing Sentry DSN");
  return "OK";
};

export const compareFigmaDesign = async (config: ApiConfig) => {
  await new Promise(resolve => setTimeout(resolve, 800));
  if (!config.figmaToken) throw new Error("Missing Figma Token");
  return { status: "OK", score: 85 };
};

export const runSafeQuery = async (config: ApiConfig, query: string) => {
  await new Promise(resolve => setTimeout(resolve, 400));
  if (!config.dbConnectionString) throw new Error("Missing DB Connection String");
  // Basic simulation of a read-only check
  if (query.toUpperCase().includes('DELETE') || query.toUpperCase().includes('DROP') || query.toUpperCase().includes('UPDATE')) {
      throw new Error("GOVERNANCE BLOCK: Unsafe query detected.");
  }
  return "Query executed successfully. 124 rows returned.";
};

// --- Confluence (Simulation) ---
export const publishConfluencePage = async (config: ApiConfig, page: { title: string, spaceKey: string, content: string }) => {
  await new Promise(resolve => setTimeout(resolve, 900));
  
  // In a real app, this would use the Atlassian REST API
  if (!config.confluenceDomain || !config.confluenceEmail || !config.confluenceToken) {
    throw new Error("Missing Confluence configuration (Domain, Email, or Token)");
  }

  console.log(`[Confluence Simulation] Publishing to ${config.confluenceDomain}/wiki/spaces/${page.spaceKey}`);
  console.log(`Title: ${page.title}`);
  
  return {
    id: `page-${Date.now()}`,
    url: `${config.confluenceDomain}/wiki/spaces/${page.spaceKey}/pages/${Date.now()}/${encodeURIComponent(page.title)}`
  };
};

// --- YouTube (Data API v3) ---
export const searchYouTubeVideos = async (config: ApiConfig, query: string) => {
  if (!config.youtubeApiKey) {
    // Fallback to simulation if no key provided
    console.warn("Missing YouTube API Key, using simulation");
    return [
      { id: 'sim1', title: `Fixing ${query} Tutorial`, thumbnail: 'https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg', channel: 'Tech Guru' },
      { id: 'sim2', title: 'Advanced Debugging Techniques', thumbnail: 'https://img.youtube.com/vi/jNQXAC9IVRw/mqdefault.jpg', channel: 'Code Master' }
    ];
  }

  const response = await fetch(`https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=2&q=${encodeURIComponent(query)}&type=video&key=${config.youtubeApiKey}`);
  
  if (!response.ok) {
    throw new Error(`YouTube API Error: ${response.status}`);
  }

  const data = await response.json();
  return data.items.map((item: any) => ({
    id: item.id.videoId,
    title: item.snippet.title,
    thumbnail: item.snippet.thumbnails.medium.url,
    channel: item.snippet.channelTitle
  }));
};